apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    password: AgBOoS3buvEC4ht5h8co9niVEnzRI0vYUMoEDAA014t4m9v/q3Q3bFhjJIKK6zZr7kuyRmMphbdvzEKbpON85kAbHVZ1k5rqo1W2aL2reUc5IeenYCW8QxzACn8YyHhvnnZjcHF3UFCn7wGMtAyVb2UsfJpfGfb2bkqU/fEpqZWcGTIeoKzxBYJF1W6v5vKZ0YDrEARNGsrxVdEPd/YIFk6TCLWWdi7sH96JdhEX7RSNbgqOpOND5vtn6pGW1HWbBhR42fS/tWKqyNKho77ArjKRfWMkJNem3/iDLP/p9Ygh4s09IV+VfGCcXgWo0pgQcSSqHC6w8ynpyfbU+h0m6/VXsoJ2MCVA3sYK/BZud6sAn2Up82/S77/AvDRPbnGGh0I9ttrcChrRwJpH6SqL1vR+BCAiGyagBPeXUqEr96TghAYyK0EHj/AktpBGDuUZM1YhdXT8slm4ztSu5W/7PdWi8jtmor+NQgEOVPtpcP7aOdOyR82D06cT93uVOfe41IdOi+KAJfIH4fmhcLGCie8QyRjey0aeP9B74tHYCrwuiTrEVFZDfRrlpP3jDchGLPDLzfl0Wjiic5rfF/hvYQ3LWbrYu0u6NKe+TmKyEJguyhVxKqxFdlo0H1GnywlhPVrEAgxJnVZtTFGR7PO5rP3ZUTFW77TjKyX7eV3Xy3xE8bAxez2mCZ1+V4YLo5lVvNHGG6e+J2XWFyLV/Lrfimdqi4hMQOwBkyr4
    user: AgAf6KmiZZs5otAUh8O48YhmIwjmIRz+kgBrmr1g/mcXetCOqPfjw6E7B2z3318HrwdmI8vD7jVrFvj4QKQtdUYLiQrvMtHukTptOd+q7Y7gEIwpf7Jcm7OTFyDthqeZ/mySJkyLiVSqGMQhf4CemHTPtHNo8z9cyM5M/MO3hCnhdGDgJ35wnaE+TzWAmr2KerFr0PMnpI1e30a7cDLYesUCbYqovvgc16Y9LfNZOlqYCIj5UHN9gcaHrC5BeHP6L2cIySyaVi4xhB7SOMGdRtpowoxBmDwFAjyvoyX21tcMaxlGuIVzZkHK9w4ooJLofAUIExFcXitsZT545tIcs1V4VLGHKE9D88bhi8/lz7/hdrSQPyPEMstEIolKJblc0OGCDKMVLa+8Kp5qE4f09A6PG8ESKzLffzL4qRlnWP3D2ZX7f4wxU/mpAqlD01R6601zjIuuwIhCQxzVOwklVkWO3FxwJJHJ2vOiJUaThY5gusUiVOr5i+RMv2BnYDUugMO8ndW+YCSVqhJAUceaXNf1z1mzfFswaUjXVXpNJEdvHqPYu5wbm+O4x4La96VJ/yAFQuehP8D4T4PR1wU4QlHZVUKjZjzNBZKSSZGFvh545QS5AvqrNvagD16CgITPZ6jwOy+9A0OJMbILcEgtVs/jl47DNNJyKdfHel53KkPVFWTJoqQeVwfH7/9ETANHwt9atU7zOZs=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: grafana-admin
      namespace: monitoring
    type: Opaque
