apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    password: AgBSmlIPVaRHq9E3iA3OuxQ9Ywe348rOJ5X9jbTUGPAs1qVZEOCfxc1LlOudo2f1JzTzSb9JSmBqK1BGj2vx0eNpF5X1Tr97sGIOc5coENi+LMmHv3ROEbWwMr0ORu4ZWm7W512fB599VFrShsbAth0Lj+uqu5zlPGaiqS7jC7RFylKllRuRTim70XKM/d4at52mrM8KwGNc9boyEPQo1L+osGf6IEIQGMvmk8XZMtxHTpO2KJuGLGnZxyGsP9MjAQKCg6UtQ+7K7ZNQC76oseL9rzd50FcqKriUUZTtKpckqt15QqJRXuK92f4R+xH2Sii+BOVSZ88Hi7Y1FR+wYgUrPHDueFunIxeSgTa7gnoSvH7d03WmmP7ES8+Qc3zYu6v2FJaeE1zy9sD934HtzHM/ig5IL9siZtXvuxVIXSa1y6T8I5FlmMNtNIAtB5nkuD42/FpoTQXtaa8C0YqUcb/LeIYqBfIBNWI0nrjcy2asnQ55BLKYHnJWrYigsI9MVGq8KovsIi9LSA6lDeKgV3QGq/iStFYxWpcYmI5AtkIFRqhR093iC7A+TPmQgVEe4kJvAwwYqarDvp1q1AkilVR81sZ3/y/GGar3j7/26WiWUUMyYllVe97MMXX2jsqE3aRRPdbkkIEYEF6KUQTf9P/HXipidWEkIpHqlWP4yRbgJMya5wM6L/FZioxCSnPnWagisJ+NQ4w1jmAuapgx
    user: AgBpwdJDmSKSRo75v16vm36uxrD7mitTCA1t9Yx6hZc9TPc0Q4a41Y++X4B2chZPRBSmFJUBWkNWLCZ1l8WjLFrjM72e5Z9okJJ/4IHupCHeJNNJaP1B9+mVTKzov7suJw6CVWjBQEt5fzDLRhRNzppamTLNxtlwAvlraE5sCRkxmHx16a+1ksoFj/JtbNZgEuv4ARyGMBkXhTRvFXHoIAlQzadmdop5Pk1bwxNxeuDFh42izRobp3bl/toX/aICuBwAT3ZLvlJ2OVwPTE2BVP5kV5txDyr4zex7quGcgRV/Lk5fa0JwH8PLLh0YvbrGnefda8twxYwImJn24szzyrYgllWz9QFo0dARm6YrMESrYahvfXNJ+WPO7f740G9z4YVHAR4/8RA+TSYEpioL4iClJhwiUy0CjdFQ99vkyG3Bykl8DjnvBIhuyH4a8M+G8zr+gkSoFKtrbc/VlXxaDAcOlrc/fu2wiUbU2pIOrf0dL0Bv11hDct+znQBPVaR47wKhsr5utPkECn4k2ZZr9u0B73T+e0Pvl5OVvi+DiBQyspcDXywHDVcVWGoUVp9xPSyLEk0TS8dsgSl2OjqaPog6P9v5TiX05pvIngafKyKENLOVsV3N99Y6tVV9nJo4Jy/HlXwS5HU2PW68A/VpdeeVoJrVUERQdA71lGUjsCTj7FDPSFUM98phyurbP3efH6bzi+7pRQ==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: grafana-admin
      namespace: monitoring
    type: Opaque
