apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    password: AgAiyNSvHGooXQtVaTFROXiyKg0W6eRNCXVIVlULgx7DSoe3+uMzsfDPA0VVmUQ7DeLQORD5md8BLrTfUaTNgbdqbBxKyThdqAvaL46AN4FpuSxxDNZ2lh5RZ0YLjnjjxdyQDa5pdn6OdEvGiOrIYtcyAv9fUzLllv+na/lWp2FOIrYtn+e2QRkPfptoNsQkGLkYqO4Y/jVuXl7oXXp60fMK7tF7IcMjg5twZA43iyt5RNdtwse9UIr9ZnK/9tjb0okGlMStAQ7AJKFJAdPXX8Pw58hA4diM97UTZyXWPGqCLarIU+yrHs0pSa8X8QfwcdmB38r8AOmp3ikxfaQcJtdniNFeuMVynkElFEglNpbsCBHXN1q63q9IpW6sBfcS3yi/MFiFhdDpsSnU2W3xFGxcRFAHbVcvTBp+Onj7I2G3ktnGznO7BHiApNZ4RQPa8klFpEp6g2EQ//csAvOEjxULEz6IgvMD02jsdvMNoTpfECehXRfPzdJaun55hpeR9tb+0MsMmoh1/nP0ULK7xKKHjaYqxX26FPSNpf4DTpBdS6gp0wgOB2iwkwwuV1actsxEiwe+i9GaO9ZtSa62FPnSsakauY1GcZuPJMq8DIHnXRiFqfbzUjRlkqGGrbOz+s9Zx6HFfHY/Tm4avKSaF3TrWE9z17dctn2KIlpRrd6LtE5VXBSlrPINB8s7FgRceM8Zc7j15zGU5juEvxbE4Xr/jyFaZze/rkxSyfhHzFFdDKYfanxKqmW22p7Dubp/
    user: AgBFwAQfT9W6sZQqa8Ewsk5raB9FVvIP3kR8hg7/YsQwkQsH42FggmuY/3QdW557WxFd2dMNF0lpmCEJRe7PCYWT0BaXWDiOi4iFvu1PLB35+eJUN9ydp4QeVg52UMOZH3IJ05wJ47vvkJPycZDipnYSZZ7eChYWFQPZ6XQQlRGW0oVkqBCVoI1AduO2ZnN0Xo1hOUAenajncQvqmuLhdndnPJJxthoUnpY/m6qNsEZLsDVa+r+EN9Txiox3lYZ/XSCD4jTbdPrqz+6vLm5TC2hB/ys0XEnb1xOE7mMvyQs1dnDk3VA5MIXTWomsnzZuY3V0eIhb/Wnf+A7Ti1SKyji7vpBrx28CrvVUbdKy0RlGPQQYEyPjb3bCr/px+aNGongxMF1bblW3Eh5RBXVmL9PoSikmkopzVv+GN5R6UERguPiFdd7/UbdEbNksLCvorp7TADycuoCHjn0LU5RZYs2XkDABHBzzo61eqe0saolg03DUY8RPB7/WQM6SsMh5I7uv5CvVCn/HBYWeVofSq6LO0Zl+K/3GGwDb/dSP99QzYWXedKkxKmrsW+di8fpwP0XhWKJ6fmWfewQjXLWlAbwaGoLscrvdv9VD37y3T6LSZVAV4gofNFkmRyDgTv0kJHyDWXUTbl6o/V2kWCu0bjbZLbdlx4rPw0Av4KPj0NQ1IOG3/bjlaNT5fS63X8GQKOYzjDKEbNQ=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: grafana-admin
      namespace: monitoring
    type: Opaque
