repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0  # Use the ref you want to point at
    hooks:
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-toml
      - id: check-yaml
        args: [
          "--allow-multiple-documents",
        ]
      - id: check-json
      - id: detect-private-key
      - id: double-quote-string-fixer
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: pretty-format-json
        args: [
          "--autofix",
        ]
      - id: trailing-whitespace
        args: [
          "--markdown-linebreak-ext", "md",
        ]
- repo: https://github.com/igorshubovych/markdownlint-cli
  rev: v0.31.1
  hooks:
  - id: markdownlint
