apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wostal-eu
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: production
  source:
    path: kustomize/overlays/production
    repoURL: https://github.com/slavic-viking/www-wostal
    targetRevision: HEAD
    kustomize:
      images:
      - slavicviking/www-wostal:76cf0b2f7513d0410b68d85f73f08eaf297e594a
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
