apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wostal-eu-staging
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: staging
  source:
    path: kustomize/overlays/staging
    repoURL: https://github.com/slavic-viking/www-wostal
    targetRevision: HEAD
    kustomize:
      images:
      - slavicviking/www-wostal:0f3b26fe8e13035624b8299f98a406d06e9e462d
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
