apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pnb-pl-staging
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: staging
  source:
    path: kustomize/overlays/staging
    repoURL: https://github.com/slavic-viking/www-pnb
    targetRevision: HEAD
    kustomize:
      images:
      - slavicviking/www-pnb:80b6ce30fc8e2ae54add0d4fbc9ec78417050788
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
